name: basic_dio_hive_app
description: Basic relay_sync example wired to local Dio and Hive adapters.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  relay_sync:
    path: ../../packages/relay_sync
  relay_sync_dio:
    path: ../../packages/relay_sync_dio
  relay_sync_flutter:
    path: ../../packages/relay_sync_flutter
  relay_sync_hive:
    path: ../../packages/relay_sync_hive

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
